import Header from '@/components/header/Header'
import './styles/globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/footer/Footer'
import 'bootstrap/dist/css/bootstrap.css'
import Script from 'next/script'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
        <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></Script>
        <Script src="https://code.jquery.com/jquery-3.6.4.min.js"></Script>
      </body>
    </html>
  )
}
